name: Build LineageOS with AVF

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout manifest
        uses: actions/checkout@v4

      - name: Install build deps
        run: sudo apt update && sudo apt install repo git unzip bc curl -y

      - name: Init LineageOS source
        run: repo init -u https://github.com/LineageOS/android.git -b lineage-23.0 -m manifest.xml

      - name: Sync sources
        run: repo sync -j$(nproc)

      - name: Download latest Pixel 8 factory image
        run: |
          curl -O https://dl.google.com/dl/android/aosp/shiba-latest-factory.zip
          unzip shiba-latest-factory.zip -d factory

      - name: Extract vendor blobs
        run: |
          cd device/google/shiba
          ./extract-files.sh ../../factory/*/image-shiba.zip

      - name: Apply AVF patches
        run: bash vendor/avf-patch.sh

      - name: Build ROM
        run: |
          source build/envsetup.sh
          lunch lineage_shiba-userdebug
          mka bacon
